/**
 * OCR text of real supplier dockets, exactly as Tesseract read them from phone photos in
 * the test bench. Regression fixtures: the parser must keep getting these right.
 */
export const REAL_DOCKETS: { id: string; products: string[]; ordered: number[] | null; lines: string[] }[] = [
  {
    id: 'bega-daily-delivery-docket (test-bench phone OCR)',
    // Every product row, in order. The docket's own layout: a column-headings row, then
    // one row per product (some wrap onto a second line), then "Total weight".
    products: [
      'Pura Milk 2Lt Bottle',
      'Pura Light Start 2Lt Bottle',
      'Dairy Choice Whole Milk 2L HDPE Bottle',
      'Dare Double Espresso 750ml BTL (6)',
      'Dare Espresso 500ml BTL (6)',
      'Dare Mocha 500ml BTL (6)',
      'DF ESL Heart Active 1L (12)',
      'FUnion Natrl Greek Style Yogurt 1kg (6)',
      'DF Protein Smoothie Choc 400mL BTL',
      'DF Protein Smoothie Banana Hny 400mL (6)',
    ],
    ordered: null,
    lines: [
      'C8        Ll 2         2.            e                                                                            1',
      'fA ho',
      'ROUTE TRANSPORT                                                               ved',
      '|                                                     DAILY DELIVERY DOCKET (PGI)         =                                   LX',
      'Metro Petroleum Truganina                                                             BDD Australia 5        NDS VIC 8012                     =',
      '2        211 Leakes Rd                                                                        PO Box 23084, DOCKLA                                    4',
      'f         TRUGANINA 3029                                General Enquiries:                1800 000 570                                                  3',
      '!                                                                     Customer Portal:                   mybega.begagroup-com-at                                  3',
      '-                                                                     Credit Services:                     creanservcesS0BES                           2',
      ':          Delivery Date              23/09/2026           Wednesday       Route           MELO11                                                             | ,',
      'Customer #:                256582                                        Trip Code:  TR896087                                                          or',
      'Customer PO #:            PO_256582_230926                        Sales Order: 0121921865                                                          E',
      'PEER.  Fmd Zoi           Product Description          Ordered Picked  Delivered     hes',
      '0827408699          2        0 3024|EA EA | Pura Milk 2Lt Bottle                             18 els             j     3',
      '0827408699          1        0 3278|EA EA | Pura Light Start 2Lt Bottle                        oj  ;',
      '0827408699           2         0 5366|EA EA | Dairy Choice Whole Milk 2L HDPE                 18 18                   24',
      'Bottle                                                        |               an Wy, 5',
      '0827408699           il         0 7774|EA EA | Dare Double Espresso 750ml BTL (6)               6     rl                    | |',
      '0827408699          1        0 7768|EA EA | Dare Espresso 500ml BTL (6)                      6   _-6|',
      '0827408699         1        0 7770|EA EA | Dare Mocha 500ml BTL (6)                      6 —5j',
      '0827408699           0         2 4155|EA EA | DF ESL Heart Active 1L (12)                         21',
      '0827408699        0       2 1141[EA EA | FUnion Natrl Greek Style Yogurt 1kg (6) 2 —2',
      '0827408699 2         10 4907|EA EA | DF Protein Smoothie Choc 400mL BTL          |                     |',
      '0827408699           1         0 4908|EA EA | DF Protein Smoothie Banana Hny           6     —6',
      '400mL (6)                                       §',
      '11] 4             |                                                     |          85 85',
      'Total weight (KG):                  120.06',
      '|',
    ],
  },
  {
    id: 'bega-daily-delivery-docket (photo as taken)',
    products: [
      'Pura Milk 2Lt Bottle',
      'Pura Light Start 2Lt Bottle',
      'Dairy Choice Whole Milk 2L HDPE Bottle',
      'Dare Double Espresso 750ml BTL (6)',
      'Dare Espresso 500ml BTL (6)',
      'Dare Mocha 500ml BTL (6)',
      'DF ESL Heart Active 1L (12)',
      'FUnion Natrl Greek Style Yogurt 1kg (6)',
      'DF Protein Smoothie Choc 400mL BTL',
      'DF Protein Smoothie Banana Hny 400mL (6)',
    ],

    // The printed Ordered column. Picked is ticked by hand and Delivered left blank.
    ordered: [18, 9, 18, 6, 6, 6, 2, 2, 12, 6],
    lines: [
      "BERNER. LV ATE PRUE STL SUS",
      "' diy \\ FY  RN\u00bb   X Fad . ye or  I!     hd                     1",
      ".       _\u2014     \u201c    -    _E   -                       -                                                                                    |",
      "& ~                                                                                                                          +",
      "a",
      "\u00bb                                      ROUTE TRANSPORT",
      "&                                                       YD EHV ERY, Doe acl Australia Pty Ltd                  :",
      "-              Metro Petroleum Truganina                                                                                            OCKLANDS vic 801",
      "+ 211LeakesRd                                                                         PO Box 23084, 0",
      "2          TRUGANINA 3029                                    General Enquiries:                  1800 000 570",
      ";                                                                   Customer Portal:                   mybega.begagroup-com-2-",
      "py                                                                   Credit Services:                     creditservicesBDD@bega-com 2X",
      "Delivery Date              23/09/2026           Wednesday       Route           MELO11",
      "<       Customer #:            256582                              Trip Code:  TR896087                                            :",
      ":           Customer PO #:            PO_256582_230926                        Sales Order: 0121921865",
      "Delivery #   pas  Eaches  eo               Product Description              Ordered Picked  Delve       3",
      "0827408699          7)         0 3024|EA EA | Pura Milk 2Lt Bottle                              18| _18             :        :",
      "0827408699          il         0 3278|EA EA | Pura Light Start 2Lt Bottle                          9    2             4      at",
      "0827408699            2          0 5366|EA EA | Dairy Choice Whole Milk 2L HDPE                   18 18                      *X",
      "Bottle                                                 TS",
      "0827408699           1         0 7774|EA EA | Dare Double Espresso 750ml BTL (6)               6      A                      3",
      "0827408699         1        0 7768|EA EA | Dare Espresso 500ml BTL (6)                    6   ~~ Ji",
      "0827408699         1       0 7770|EA EA | Dare Mocha 500ml BTL (6)                     6; \u2014Bj",
      "0827408699         0       2 4155|EA EA | DF ESL Heart Active 1L (12)                     2 Sa",
      "0827408699         0       2 1141|EA EA | FUnion Natrl Greek Style Yogurt 1kg (6)          2 2 ), Ao.   |     |",
      "0827408699            2          0 4907|EA EA | DF Protein Smoothie Choc 400mL BTL             12 i",
      "(6)                                                          _",
      "0827408699           1          0 4908 |EA EA | DF Protein Smoothie Banana Hny                   6     \u20146",
      "400mL (6)                                                 | Rie",
      "11         4                                                                       8s| 85)",
      "Total weight (KG):                  120.06",
    ],
  },
  {
    id: 'bega-daily-delivery-docket (photo cleaned up (grey, contrast, enlarged))',
    products: [
      'Pura Milk 2Lt Bottle',
      'Pura Light Start 2Lt Bottle',
      'Dairy Choice Whole Milk 2L HDPE Bottle',
      'Dare Double Espresso 750ml BTL (6)',
      'Dare Espresso 500ml BTL (6)',
      'Dare Mocha 500ml BTL (6)',
      'DF ESL Heart Active 1L (12)',
      'FUnion Natrl Greek Style Yogurt 1kg (6)',
      'DF Protein Smoothie Choc 400mL BTL',
      'DF Protein Smoothie Banana Hny 400mL (6)',
    ],

    // The printed Ordered column. Picked is ticked by hand and Delivered left blank.
    ordered: [18, 9, 18, 6, 6, 6, 2, 2, 12, 6],
    lines: [
      "Nee        v           Wi                                                                   1",
      "x",
      ";                                                           8e9%,",
      "ROUTE TRANSPORT",
      ";                                                    DAILY DELIVERY DOCKET (PGI)         i",
      "Metro Petroleum Truganina                                                                   spo ALES         NDS VIC 8012",
      "7?        211 Leakes Rd                                                                        pO Box 23084, DOCKLA",
      "Ke          TRUGANINA 3029                                   General Enquiries:                  1800 000 570",
      "Customer Portal:                   mybega begagroup-com 2",
      "a                                                                   Credit Services:                     creditservicesBDD@bega.com-2",
      "Delivery Date              23/09/2026           Wednesday       Route           MELO11",
      "~     Customer #:        256582                    Trip Code:  TR896087",
      "Customer PO #:            PO_256582_230926                        Sales Order: 0121921865                                              i",
      "Delivery #   pas  Eaches  {5% ie               Product Description              Ordered Picked  Dele",
      "0827408699           2         0 3024 |EA EA | Pura Milk 2Lt Bottle                               18    _A8            \u2014",
      "0827408699          1         0 3278|EA EA | Pura Light Start 2Lt Bottle                          9    A)             i         {",
      "0827408699            2          0 5366|EA EA | Dairy Choice Whole Milk 2L HDPE                   18 18                          ;",
      "Bottle                                                             Ee",
      "0827408699           1         0 7774|EA EA | Dare Double Espresso 750ml BTL (6)                6     A",
      "0827408699        1       0 7768|EA EA | Dare Espresso 500ml BTL (6)                  6| oo] FEE",
      "0827408699         1       0 7770|EA EA | Dare Mocha 500ml BTL (6)                     6 \u2014Bj",
      "0827408699        0       2 4155|EA EA | DF ESL Heart Active 1L (12)                   2| oA",
      "0827408699          0         2 1141|EA EA | FUnion Natrl Greek Style Yogurt 1kg (6)         y 2 2 i aro",
      "0827408699           2          0 4907|EA EA | DF Protein Smoothie Choc 400mL BTL             12| 7",
      "(6)                                                      |",
      "0827408699            1          0 4908|EA EA | DF Protein Smoothie Banana Hny                    6     \u20146",
      "400mL (6)                                            | eS",
      "11         4                                                                       85 85",
      "Total weight (KG):       120.06",
    ],
  },
  {
    id: 'bega-daily-delivery-docket (photo cleaned up by the test bench in Chromium)',
    products: [
      'Pura Milk 2Lt Bottle',
      'Pura Light Start 2Lt Bottle',
      'Dairy Choice Whole Milk 2L HDPE Bottle',
      'Dare Double Espresso 750ml BTL (6)',
      'Dare Espresso 500ml BTL (6)',
      'Dare Mocha 500ml BTL (6)',
      'DF ESL Heart Active 1L (12)',
      'FUnion Natrl Greek Style Yogurt 1kg (6)',
      'DF Protein Smoothie Choc 400mL BTL',
      'DF Protein Smoothie Banana Hny 400mL (6)',
    ],

    ordered: [18, 9, 18, 6, 6, 6, 2, 2, 12, 6],
    lines: [
      "=         OE       >    \u00bb        wr          \u2018,                                                                   1",
      "x",
      "Bed",
      "ROUTE TRANSPORT",
      ":                                                        DAILY DELIVERY DOCKET acl. Australia Pty Ltd",
      "Metro Petroleum Truganina                                                                                         KLANDS vic 8012",
      "<2?        211 Leakes Rd                                                                           PO Box 23084, DOC",
      "TRUGANINA 3029                                  General Enquiries:                 1800 000 570",
      "Customer Portal:                   mybega.begagroup-com-24",
      "\u00bb                                                                   Credit Services:                     creditservicesBDD@bega.com 2",
      "Delivery Date              23/09/2026           Wednesday       Route           MELO11",
      "Customer #:           256582                            Trip Code:  TR896087",
      "Customer PO #:            PO_256582_230926                        Sales Order: 0121921865                                               3",
      "Delivery #   ond  Eaches  So              Product Description             Ordered Picked  Deliveisy",
      "0827408699         2        0 3024|EA EA | Pura Milk 2Lt Bottle                            18 _8            I     |",
      "0827408699         1        0 3278|EA EA | Pura Light Start 2Lt Bottle                       9 2            |",
      "0827408699            2          0 5366|EA EA | Dairy Choice Whole Milk 2L HDPE                   18      Pt                          ;",
      "Bottle                                                          a a",
      "0827408699         1        0 7774|EA EA | Dare Double Espresso 750ml BTL (6)             6     Sf                 1",
      "0827408699         1       0 7768|EA EA | Dare Espresso 500ml BTL (6)                    6   _\u2014%| J ine",
      "0827408699           1         0 7770|EA EA | Dare Mocha 500ml BTL (6)                         6    \u20146",
      "0827408699         0       2 4155|EA EA | DF ESL Heart Active 1L (12)                     2    2  Sma",
      "0827408699        0      2 1141|EA EA | FUnion Natrl Greek Style Yogurt 1kg (6)        2  2 il li",
      "0827408699            2          0 4907|EA EA | DF Protein Smoothie Choc 400mL BTL              12| 2",
      "(6)                                                      | |",
      "0827408699           1          0 4908|EA EA | DF Protein Smoothie Banana Hny                   6     \u20146",
      "400mL (6)                                               | AE",
      "11        4                                                                   85 85",
      "Total weight (KG):                  120.06",
    ],
  },
];
